### ISSUE TITLE
[IDG-A33X/IDG-A32X] PFD unavailable after a cold start

### ISSUE THREAD

**Issue by gpenin** [it0uchpods/IDG-A33X#2]
Using Flightgear 2017.3.1, after a cold start, the PFD is unavailable :

![fgfs-screen-001](https://user-images.githubusercontent.com/17027329/38458123-965090b0-3a9a-11e8-970d-2575f27c7791.png)

The PFD is correctly displayed if using the "auto start" functionality.

### Expected Behavior
The PFD should be correctly displayed.

### Current Behavior
The PFD is unavailable.

**Comment by merspieler** [comment]
If you start from cold and dark, this behaviour is correct, if the ADIRS aren't aligned...
You have to turn the knowbs on the top left corner to the `NAV` position.
As well, you have to start the alignment on the INIT A page in the MCDU (option available after current airport and destination was entered [right lsk3])

**Comment by it0uchpods** [comment]
@merspieler is correct here.

You need to switch on the ADIRS in the Overhead, and press FMGC --> INIT --> DEP/ARR (ex: KSFO/KLAX) then, ALIGN IRS

Kind Regards,
Josh

**Comment by gpenin** [comment]
Thank you very much @merspieler and @it0uchpods for these explanations. I also did all these steps but didn't know that it was necessary to wait a few minutes for the alignment, which then leads to a fully functionnal PFD.

Best regards.

**Comment by it0uchpods** [comment]
Great to hear! It's roughly 10 minutes by default, but you can skip this in the aircraft config menu.

Enjoy,
Josh

**Comment by merspieler** [comment]
`IR IN ALIGN X MIN` message would make that more clear...

**Comment by it0uchpods** [comment]
Well when the ECAM system is ready, you will see it.

J

**Comment by merspieler** [comment]
ofc
