### ISSUE TITLE
Phi PFD WebPanel stopped working

### ISSUE THREAD

**Issue by jonititan** [it0uchpods/IDG-A33X#3]
### Expected Behavior

The Phi PFD webpanel example should mirror the behaviour of the PFD in flightgear.
In a recent update it stopped working 

### Current Behavior

The PFD example and the PFD widget do not move or display altitude or airspeed

### Possible Solution

I think in a recent commit the property tree was changed.
e.g. /orientation/roll-deg was changed to /orientation/model/pitch-deg so now the knockout bindings are looking for values on a node that no longer exists or is not updated.

The airspeed and altitude in the widget look for their values from
/position/altitude-ft and /velocities/airspeed-kt
looking at the property tree of the current aircraft version in Phi it can be seen that these nodes are shown but either display 0 or null.

### Steps to Reproduce

1. Start FGFS selecting an IDG-A33X aircraft.  I use A330-300-RR remember to set http out...
2. Open Phi using Equipment -> Map (Opens in browser)
3. Look at the sidebar widget during flight and you should see it is not being updated

**Comment by jonititan** [comment]
Looks like the map in Phi is also not working so there may me more things on the property tree that have changed.  Looking in Phi/main.js it looks like the map pulls data from /position/latitude-deg and /position/longitude-deg a quick look in the fgfs session shows the map works there it is just in Phi that there is a problem.

Not sure how helpful this is but here is a list of the property tree nodes the Phi uses (not including examples)

        gmt : "/sim/time/gmt",
        timeWarp : "/sim/time/warp",

        // flight
        pitch : "/orientation/pitch-deg",
        roll : "/orientation/roll-deg",
        heading : "/orientation/heading-magnetic-deg",
        "true-heading" : "/orientation/heading-deg",
        altitude : "/position/altitude-ft",
        latitude : "/position/latitude-deg",
        longitude : "/position/longitude-deg",
        airspeed : "/velocities/airspeed-kt",
        groundspeed : "/velocities/groundspeed-kt",
        slip : "/instrumentation/slip-skid-ball/indicated-slip-skid",
        cg : "/fdm/jsbsim/inertia/cg-x-in",
        weight : "/fdm/jsbsim/inertia/weight-lbs",

        // radio settings
        com1stn : "/instrumentation/comm/station-name",
        com1use : "/instrumentation/comm/frequencies/selected-mhz",
        com1sby : "/instrumentation/comm/frequencies/standby-mhz",
        com1stn : "/instrumentation/comm/station-name",
        com2stn : "/instrumentation/comm[1]/station-name",
        com2use : "/instrumentation/comm[1]/frequencies/selected-mhz",
        com2sby : "/instrumentation/comm[1]/frequencies/standby-mhz",
        com2stn : "/instrumentation/comm[1]/station-name",
        nav1use : "/instrumentation/nav/frequencies/selected-mhz",
        nav1sby : "/instrumentation/nav/frequencies/standby-mhz",
        nav1stn : "/instrumentation/nav/nav-id",
        nav2use : "/instrumentation/nav[1]/frequencies/selected-mhz",
        nav2sby : "/instrumentation/nav[1]/frequencies/standby-mhz",
        nav2stn : "/instrumentation/nav[1]/nav-id",
        adf1use : "/instrumentation/adf/frequencies/selected-khz",
        adf1sby : "/instrumentation/adf/frequencies/standby-khz",
        adf1stn : "/instrumentation/adf/ident",
        dme1use : "/instrumentation/dme/frequencies/selected-mhz",
        dme1dst : "/instrumentation/dme/indicated-distance-nm",
        xpdrcod : "/instrumentation/transponder/id-code",
        // weather
        "ac-wdir" : "/environment/wind-from-heading-deg",
        "ac-wspd" : "/environment/wind-speed-kt",
        "ac-visi" : "/environment/visibility-m",
        "ac-temp" : "/environment/temperature-degc",
        "ac-dewp" : "/environment/dewpoint-degc",
        "gnd-wdir" : "/environment/config/boundary/entry/wind-from-heading-deg",
        "gnd-wspd" : "/environment/config/boundary/entry/wind-speed-kt",
        "gnd-visi" : "/environment/config/boundary/entry/visibility-m",
        "gnd-temp" : "/environment/config/boundary/entry/temperature-degc",
        "gnd-dewp" : "/environment/config/boundary/entry/dewpoint-degc",
        "metar-valid" : "/environment/metar/valid"

**Comment by jonititan** [comment]
Further testing determined this to be an issue with my UDP setup.  The UDP work I was doing caused a clash with the websocket configuration Phi was using.  Apologies for the waste of time.

**Comment by it0uchpods** [comment]
No problem. Glad it's sorted.
