### ISSUE TITLE
Freighter liveries broken for Linux users

### ISSUE THREAD

**Issue by D-Sven** [it0uchpods/IDG-A33X#7]
Linux users can't see any liveries on the A330-223F/A330-243F.

### Possible Solution

Rename Models/243f_blank.png to 243**F**_blank.png with capital letter F fixes the problem.
### Steps to Reproduce

1.
2.
3.
4.

**Comment by legoboyvdlp** [comment]
@merspieler you have linux, correct? Can you check and confirm (and maybe fix?)

**Comment by legoboyvdlp** [comment]
the fix works or the liveries work (you do not see the bug)?

**Comment by merspieler** [comment]
I can see all liveries on the A330-223F and A330-243F

**Comment by it0uchpods** [comment]
That is a problem on YOUR git... on github and my local, shows with a capital F in the ac file, and the png itself.

I think we fixed this a while ago, but git did not notice on your system.

Kind Regards,
Josh
